# Generated by Django 5.0.1 on 2024-01-28 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff_profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Admin_Profile',
        ),
        migrations.DeleteModel(
            name='Staff_Profile',
        ),
        migrations.DeleteModel(
            name='User_Profile',
        ),
    ]
